global using BlogPOC.Application.Interfaces;
global using BlogPOC.Application.Services;
global using BlogPOC.Core.Entities;
global using BlogPOC.Core.Interfaces;
global using BlogPOC.Infrastructure.Data;
global using BlogPOC.Infrastructure.Repositories;
global using BLOGPOC.Application.Services;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
