version: '3.4'

services:
  blogpoc.webapi:
    image: ${DOCKER_REGISTRY-}blogpocwebapi
    build:
      context: .
      dockerfile: BlogPOC.WebAPI/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BlogDb;User=sa;Password=Your_password123;TrustServerCertificate=true; 
    depends_on:
      - sqlserver

  blogpoc.userapi:
    image: ${DOCKER_REGISTRY-}blogpocuserapi
    build:
      context: .
      dockerfile: BlogPOC.UserAPI/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"